### ISSUE TITLE
fd_controller load error

### ISSUE THREAD

**Issue by CarlDegio** [ICube-Robotics/forcedimension_ros2#2]
I use this sdk in ros foxy, Omega.3.

the launch file load three controller, fd_controller, joint_state_broadcaster and ee_pose_broadcaster. However, the fd_controller seems no source code. Thus, the loading occur an error.
![IMG_20221228_162958](https://user-images.githubusercontent.com/52379582/209783347-4843d074-51bb-48f3-8ed0-cbbcfffb1865.jpg)

missing of fd_controller means can not control Omega by ros command. How to solve it?

**Comment by CarlDegio** [comment]
ros2_control and ros2_controller should be added in package.xml depend

**Comment by mcbed** [comment]
Hi, you are right ! feel free to propose a PR to fix it.
